### ISSUE TITLE
Error during running main-py (even when using run as adminsitrator)

### ISSUE THREAD

**Issue by TawfikDaim** [Hassassistant/Haaska#3]
Role created successfully. ARN:  arn:aws:iam::815421264176:role/HaaskaLambdaRole
Policies attached successfully.
config.json has been updated.
haaska.zip has been created.
Traceback (most recent call last):
  File "C:\Users\tawfi\Downloads\main.py", line 99, in <module>
    response = client.create_function(
  File "C:\Users\tawfi\AppData\Local\Programs\Python\Python310\lib\site-packages\botocore\client.py", line 565, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\Users\tawfi\AppData\Local\Programs\Python\Python310\lib\site-packages\botocore\client.py", line 1021, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDeniedException) when calling the CreateFunction operation: None

Anyone faced something like this?

**Comment by TawfikDaim** [comment]
I do need to remove the role to try again, but always face the same issue like above

**Comment by TawfikDaim** [comment]
Answering my own comment, 
it turned out that AWS blocked my user ID and hence the AccessDeniedException
